#define ATS_PACKNAME "ATSCC2LUA.qlistref"
#define ATS_EXTERN_PREFIX "ats2luapre_"
#define LIBATSCC_targetloc "$PATSHOME/contrib/libatscc/ATS2-0.3.2"
#staload "./basics.sats"
#include "{$LIBATSCC}/SATS/qlistref.sats"
